### ISSUE TITLE
入力中はリロードされないように

### ISSUE THREAD

**Issue by youmjww** [mikankari/timesline#7]
# 背景
極稀にテキストボックスに文字を入力中にリロードが挟まり、つぶやき直しになることがある

# 解決案
https://github.com/mikankari/timesline/blob/master/index.php#L34
ここをjsに移植して

```javascript
if (テキストボックスが空) {
  setTimeout("location.reload()", 18000);
}
```
でできそうな気がする

**Comment by mikankari** [comment]
社内向け反映済み。
オワタので閉じる。
